### PR TITLE
Update pronouns to be more inclusive

### PR DESCRIPTION
**Pull request by melanierichards**
Finally got the chance to change these pronouns up!

Notes:
- I combined 2 sentences so that they read a little more naturally.
- There's two lines in the `getTitle()` function that I left because I'm not sure what you'd like to do with them. They reference "superman" and "superwoman".

### CODE REVIEW

**Comment by bevacqua** [comment]
Superbeing?

**Comment by melanierichards** [comment]
"Superhuman" could work, too. Wasn't sure if you wanted to change both the lines or merge them (do the #s correspond to languages?).

Also I just realized there's a copy of hubby.js in dist that I missed, working on that shortly.

**Comment by bevacqua** [comment]
That's compiled iirc, and there's also the fact that you PRed against `master` but the site lives on `gh-pages` because GitHub

**Comment by melanierichards** [comment]
Hmm, I think I'm missing how that's getting compiled. Is there a command I should be running?

I can resubmit a PR against gh-pages.

**Comment by bevacqua** [comment]
Yup. `npm run start` for development and `npm run build` for deployment.

https://github.com/bevacqua/hubby/blob/master/package.json#L16-L19

**Comment by melanierichards** [comment]
Thanks!

**Pull request merged**
